#spring.datasource.url=jdbc:postgresql://postgres:5432/postgres?currentSchema=urun_takip --Docker bağlantısı için
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=urun_takip
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=busra
spring.datasource.password=busra
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG

server.port=8088

