apiVersion: apps/v1
kind: Deployment
metadata:
  name: busra-app
  labels:
    app: busra-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busra-app
  template:
    metadata:
      labels:
        app: busra-app
    spec:
      containers:
        - name: busra-app
          image: busravarisli/busratask:0.0.2
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/postgres?currentSchema=urun_takip"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: busra-app
spec:
  selector:
    app: busra-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
